/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/量筒': RouteRecordInfo<'/posts/量筒', '/posts/量筒', Record<never, never>, Record<never, never>>,
    '/posts/数逻': RouteRecordInfo<'/posts/数逻', '/posts/数逻', Record<never, never>, Record<never, never>>,
    '/posts/数字系统设计': RouteRecordInfo<'/posts/数字系统设计', '/posts/数字系统设计', Record<never, never>, Record<never, never>>,
    '/posts/通网': RouteRecordInfo<'/posts/通网', '/posts/通网', Record<never, never>, Record<never, never>>,
    '/posts/AI': RouteRecordInfo<'/posts/AI', '/posts/AI', Record<never, never>, Record<never, never>>,
    '/posts/Antenna': RouteRecordInfo<'/posts/Antenna', '/posts/Antenna', Record<never, never>, Record<never, never>>,
    '/posts/Computer-Network': RouteRecordInfo<'/posts/Computer-Network', '/posts/Computer-Network', Record<never, never>, Record<never, never>>,
    '/posts/cpp-multi-file': RouteRecordInfo<'/posts/cpp-multi-file', '/posts/cpp-multi-file', Record<never, never>, Record<never, never>>,
    '/posts/CSAPP学习笔记': RouteRecordInfo<'/posts/CSAPP学习笔记', '/posts/CSAPP学习笔记', Record<never, never>, Record<never, never>>,
    '/posts/DataAndAlgorithms': RouteRecordInfo<'/posts/DataAndAlgorithms', '/posts/DataAndAlgorithms', Record<never, never>, Record<never, never>>,
    '/posts/Digital-Signal-Processing': RouteRecordInfo<'/posts/Digital-Signal-Processing', '/posts/Digital-Signal-Processing', Record<never, never>, Record<never, never>>,
    '/posts/DRL': RouteRecordInfo<'/posts/DRL', '/posts/DRL', Record<never, never>, Record<never, never>>,
    '/posts/github-command': RouteRecordInfo<'/posts/github-command', '/posts/github-command', Record<never, never>, Record<never, never>>,
    '/posts/hello-valaxy': RouteRecordInfo<'/posts/hello-valaxy', '/posts/hello-valaxy', Record<never, never>, Record<never, never>>,
    '/posts/hello-world': RouteRecordInfo<'/posts/hello-world', '/posts/hello-world', Record<never, never>, Record<never, never>>,
    '/posts/Introduction-to-Probability': RouteRecordInfo<'/posts/Introduction-to-Probability', '/posts/Introduction-to-Probability', Record<never, never>, Record<never, never>>,
    '/posts/Physics': RouteRecordInfo<'/posts/Physics', '/posts/Physics', Record<never, never>, Record<never, never>>,
    '/posts/PhysicsExercise': RouteRecordInfo<'/posts/PhysicsExercise', '/posts/PhysicsExercise', Record<never, never>, Record<never, never>>,
    '/posts/Python-OJ': RouteRecordInfo<'/posts/Python-OJ', '/posts/Python-OJ', Record<never, never>, Record<never, never>>,
    '/posts/Signal-and-Systems': RouteRecordInfo<'/posts/Signal-and-Systems', '/posts/Signal-and-Systems', Record<never, never>, Record<never, never>>,
    '/posts/Speech-SP': RouteRecordInfo<'/posts/Speech-SP', '/posts/Speech-SP', Record<never, never>, Record<never, never>>,
    '/posts/StaSP': RouteRecordInfo<'/posts/StaSP', '/posts/StaSP', Record<never, never>, Record<never, never>>,
    '/posts/Stochastic-Process': RouteRecordInfo<'/posts/Stochastic-Process', '/posts/Stochastic-Process', Record<never, never>, Record<never, never>>,
    '/posts/stuffs': RouteRecordInfo<'/posts/stuffs', '/posts/stuffs', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
