name: Hexo Deploy Automatically

on:
  push:
    branches:
      # The branch where the project source code resides
      # 项目源代码所在的分支
      - hexo


jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Fix timestamps
      - name: restore timestamps
        uses: step-security/git-restore-mtime-action@v2
      # Step 4. （可选）查看结果
      - name: Verify timestamps
        run: |
          stat source/_posts/* || true
          find . -type f | head -n 3 | xargs stat -c '%y %n'

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Generate
        run: |
          npm i && npx hexo g
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: main
          publish_dir: ./public
          force_orphan: true
